package br.gov.caixa.siavl.atendimentoremoto.constants;

public final class Constants {

	private Constants() {
		throw new IllegalStateException("Utility class");
	}

	public static final String[] CLASSE_DOCUMENTOS = new String[] {
			"CNH", "CARTEIRA_IDENTIDADE", "DEMONSTRATIVO_PAGAMENTO", "DOCUMENTO_CONCESSIONARIA", "EXTRATO_CONTA ",
			"CTPS", "DECLARACAO_IRPF", "EXTRATO_FGTS", "EXTRATO_APLICACAO", "FATURA_CARTAO_CREDITO",
			"BOLETO_BANCARIO_HABITACIONAL", "CARTEIRA_FUNCIONAL", "CARTEIRA_IDENTIDADE_MILITAR", "PASSAPORTE",
			"CONTRATO_CDC", "CONTRATO_CONSIGNADO", "CONTRATO_CREDITO_PESSOAL", "CONTRATO_FINANCIAMENTO_VEICULO",
			"CONTRATO_CHEQUE_ESPECIAL", "CONTRATO_ADESAO_HOMEBROKER", "NOTA_NEGOCIACAO_LCI", "NOTA_NEGOCIACAO_CDB",
			"PEDIDO_OFERTA_PUBLICA", "TERMO_ADESAO_INSS", "PROPOSTA_SEGURO_PRESTAMISTA",
			"CANCELAMENTO_SEGURO_PRESTAMISTA", "ANALISE_PERFIL_INVESTIDOR", "CONTRATACAO_CARTAO_VA_VR",
			"CONTRATACAO_GIRO_CAIXA", "CONTRATO_CHEQUE_EMPRESA", "CONTRATO_FAMPE", "CONTRATO_DESCONTO_CHEQ_PRE_DAT",
			"CONTRATO_GIRO_CAIXA_INST_MULTIP", "CONTRATO_RENEGOCIACAO_PJ", "CONTRATO_PRONAMPE",
			"DOCUMENTO_CONSTITUICAO_PJ", "CONTRATO_SOCIAL", "DOCUMENTO_FATURAMENTO_DOSSIEPJ",
			"CERTIFICADO_MICROEMPREENDEDOR_DOSSIEPJ", "REQUERIMENTO_EMPRESARIO_DOSSIEPJ"
	};
}
