pipeline { 

    agent {label 'jdk17'}
    options { timeout(time: 20, unit: 'MINUTES')}
    enviroment {
        DEV_DEPLOY = true
        buildArtifactScript = "mvn clean package"
        sonarTest = "src/test/java"

    } 
    stages { 
        stage ('Initialise') { 
            steps { 
                stepInitialise()
            }
        }

        stage('build package') {
            steps { 
                sh "${buildArtifactScript}"
            }
        }

        stage('Sonar Analysis'){ 
            steps { 
                stepMavenSonarAnalysis(["sonar.test":"${sonarTest}"])
            }
        }

        stage('Run BlackDuck Scan') {
            steps {
              stepBlackDuckScan()
            }
        }

        stage('Build container image'){
            steps{
                stepContainerImageBuild()
            }
        }

        stage('Build ECS deployment image'){
            steps {
                  stepEcsDeploymentImageBuild()
            }
        }

        stage('Publish to uDeploy'){
            steps {
                  stepEcsUdeployPublish()
            }
        }
        
    }

    post {
        always {     
            stepFinalise()
            stepReflexionUpload(LS_TEAM_NAME: 'devops', LS_PIPELINE_TYPE:'maven')
        }
    }
}
