package br.gov.caixa.siavl.atendimentoremoto.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import br.gov.caixa.siavl.atendimentoremoto.model.ModeloNotaNegocio;

@Repository
public interface ModeloNotaRepository extends JpaRepository<ModeloNotaNegocio, Long> {
	
	@Query(value = "SELECT A.NU_MODELO_NOTA_NEGOCIO, A.IC_CONTRATACAO_AUTOMATICA, B.NU_ACAO_PRODUTO, B.DE_ACAO_PRODUTO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB020_ACAO_PRODUTO B WHERE A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO AND A.IC_SITUACAO_MODELO_NOTA = 'P' AND A.IC_MODELO_NOTA_ATIVO = '1' AND B.IC_ATIVO = '1' AND A.IC_CONTRATACAO_AUTOMATICA = 'S' AND B.NU_ACAO_PRODUTO =?1 ORDER BY A.NU_MODELO_NOTA_NEGOCIO ASC", nativeQuery = true)
	List<Object[]> modelosByProduto(Long idAcaoProduto);
	
	@Query(value = "SELECT A.NU_MODELO_NOTA_NEGOCIO, A.IC_CONTRATACAO_AUTOMATICA, B.NU_ACAO_PRODUTO, B.DE_ACAO_PRODUTO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB020_ACAO_PRODUTO B WHERE A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO AND A.IC_SITUACAO_MODELO_NOTA = 'P' AND A.IC_MODELO_NOTA_ATIVO = '1' AND B.IC_ATIVO = '1' AND A.IC_CONTRATACAO_AUTOMATICA = 'S' ORDER BY A.NU_MODELO_NOTA_NEGOCIO ASC", nativeQuery = true)
	List<Object[]> modelos();
	
	@Query(value="SELECT A.NU_MODELO_NOTA_NEGOCIO, B.NU_CAMPO_MODELO_NOTA, B.NU_ORDEM_CAMPO_MODELO, C.NO_CAMPO_MODELO_NOTA, C.IC_CAMPO_DEFINIDO, C.IC_CAMPO_EDITAVEL, C.IC_CAMPO_OBRIGATORIO, C.DE_ESPACO_RESERVADO, C.IC_TIPO_DADO_CAMPO, C.IC_TIPO_ENTRADA_CAMPO, C.DE_CAMPO, C.QT_CARACTER_CAMPO, C.VR_INICIAL_CAMPO, C.CO_MASCARA_CAMPO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB018_CAMPO_MODELO B,  AVL.AVLTB017_CAMPO_MODELO_NOTA C WHERE A.NU_MODELO_NOTA_NEGOCIO = B.NU_MODELO_NOTA_NEGOCIO AND  B.NU_CAMPO_MODELO_NOTA = C.NU_CAMPO_MODELO_NOTA AND A.NU_MODELO_NOTA_NEGOCIO =?1 GROUP BY A.NU_MODELO_NOTA_NEGOCIO, B.NU_CAMPO_MODELO_NOTA, B.NU_ORDEM_CAMPO_MODELO, C.NO_CAMPO_MODELO_NOTA, C.IC_CAMPO_DEFINIDO, C.IC_CAMPO_EDITAVEL, C.IC_CAMPO_OBRIGATORIO, C.DE_ESPACO_RESERVADO, C.IC_TIPO_DADO_CAMPO, C.IC_TIPO_ENTRADA_CAMPO, C.DE_CAMPO, C.QT_CARACTER_CAMPO, C.VR_INICIAL_CAMPO, C.CO_MASCARA_CAMPO ORDER BY B.NU_ORDEM_CAMPO_MODELO ASC", nativeQuery=true)
	List<Object[]> detalhesModelo(Long idModeloNota);
	
	@Query(value="SELECT A.NU_MODELO_NOTA_NEGOCIO, B.NU_CAMPO_MODELO_NOTA, B.NU_ORDEM_CAMPO_MODELO, C.NO_CAMPO_MODELO_NOTA, C.IC_CAMPO_DEFINIDO, C.IC_CAMPO_EDITAVEL, C.IC_CAMPO_OBRIGATORIO, C.DE_ESPACO_RESERVADO, C.IC_TIPO_DADO_CAMPO, C.IC_TIPO_ENTRADA_CAMPO, C.DE_CAMPO, C.QT_CARACTER_CAMPO, C.VR_INICIAL_CAMPO, C.CO_MASCARA_CAMPO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB018_CAMPO_MODELO B,  AVL.AVLTB017_CAMPO_MODELO_NOTA C WHERE A.NU_MODELO_NOTA_NEGOCIO = B.NU_MODELO_NOTA_NEGOCIO AND  B.NU_CAMPO_MODELO_NOTA = C.NU_CAMPO_MODELO_NOTA AND A.NU_MODELO_NOTA_NEGOCIO =?1 GROUP BY A.NU_MODELO_NOTA_NEGOCIO, B.NU_CAMPO_MODELO_NOTA, B.NU_ORDEM_CAMPO_MODELO, C.NO_CAMPO_MODELO_NOTA, C.IC_CAMPO_DEFINIDO, C.IC_CAMPO_EDITAVEL, C.IC_CAMPO_OBRIGATORIO, C.DE_ESPACO_RESERVADO, C.IC_TIPO_DADO_CAMPO, C.IC_TIPO_ENTRADA_CAMPO, C.DE_CAMPO, C.QT_CARACTER_CAMPO, C.VR_INICIAL_CAMPO, C.CO_MASCARA_CAMPO ORDER BY B.NU_ORDEM_CAMPO_MODELO ASC", nativeQuery=true)
	List<Object[]> modeloNotaDinamico(Long idModeloNota);
	
	@Query(value="SELECT A.NO_MODELO_NOTA_NEGOCIO, C.NO_ABREVIADO_PRDTO, B.NU_ACAO_PRODUTO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB020_ACAO_PRODUTO B, AVL.AVLVM003_PRODUTO C WHERE A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO AND B.NU_PRODUTO = C.NU_PRODUTO AND A.NU_MODELO_NOTA_NEGOCIO = ?1", nativeQuery=true)
	List<Object[]> notaProduto(Long idModeloNota);
	
	@Query("SELECT N FROM ModeloNotaNegocio N WHERE ROWNUM <= 1 AND N.numeroModeloNota = ?1")
	ModeloNotaNegocio prazoValidade(Long numeroModeloNota);

	@Query(value = "SELECT A.NU_MODELO_NOTA_NEGOCIO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB020_ACAO_PRODUTO B WHERE A.NU_MODELO_NOTA_NEGOCIO NOT IN (SELECT C.NU_MODELO_NOTA_NEGOCIO FROM AVL.AVLTB030_FLUXO_ATNTO_MODELO C) AND A.IC_MODELO_VINCULA_DOCUMENTO = 0 AND A.IC_MODELO_NOTA_ATIVO = 1 AND A.IC_SITUACAO_MODELO_NOTA = 'P' AND A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO AND B.IC_ATIVO = 1 AND A.NU_MODELO_NOTA_NEGOCIO = ?1", nativeQuery = true)
	Optional<Long> vinculaDocumento(Long numeroModeloNota);
	
	@Query(value="SELECT A.NU_MODELO_NOTA_NEGOCIO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A INNER JOIN AVL.AVLTB020_ACAO_PRODUTO B ON(A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO) WHERE B.IC_ATIVO = 1 AND A.IC_MODELO_NOTA_ATIVO = 1 AND A.IC_SITUACAO_MODELO_NOTA = 'P' AND A.IC_CONTRATACAO_AUTOMATICA = 'S' AND A.NU_MODELO_NOTA_NEGOCIO NOT IN (SELECT C.NU_MODELO_NOTA_NEGOCIO FROM AVL.AVLTB030_FLUXO_ATNTO_MODELO C) AND A.NU_MODELO_NOTA_NEGOCIO = ?1", nativeQuery = true)
	Optional<Long> notaValida(Long numeroModeloNota);
	
	@Query(value="SELECT B.NU_ACAO_PRODUTO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A INNER JOIN AVL.AVLTB020_ACAO_PRODUTO B ON(A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO) WHERE B.IC_ATIVO = 1 AND A.IC_MODELO_NOTA_ATIVO = 1 AND A.IC_SITUACAO_MODELO_NOTA = 'P' AND A.IC_CONTRATACAO_AUTOMATICA = 'S' AND A.NU_MODELO_NOTA_NEGOCIO NOT IN (SELECT C.NU_MODELO_NOTA_NEGOCIO FROM AVL.AVLTB030_FLUXO_ATNTO_MODELO C) AND B.NU_ACAO_PRODUTO = ?1 AND A.NU_MODELO_NOTA_NEGOCIO = ?2", nativeQuery = true)
	Optional<Long> modeloProdutoValido(Long numeroAcaoProduto, Long numeroModeloNota);
	
	@Query(value="SELECT A.NO_MODELO_NOTA_NEGOCIO, C.NO_ABREVIADO_PRDTO, B.NU_ACAO_PRODUTO FROM AVL.AVLTB005_MODELO_NOTA_NEGOCIO A, AVL.AVLTB020_ACAO_PRODUTO B, AVL.AVLVM003_PRODUTO C WHERE A.NU_ACAO_PRODUTO = B.NU_ACAO_PRODUTO AND B.NU_PRODUTO = C.NU_PRODUTO AND A.NU_MODELO_NOTA_NEGOCIO = ?1", nativeQuery=true)
	List<Object[]> modeloNotaProduto(Long idModeloNota);
}
