CREATE TABLE AVL.AVLTB020_ACAO_PRODUTO (
	NU_ACAO_PRODUTO NUMBER(9,0),
	DE_ACAO_PRODUTO VARCHAR2(100),
	NU_PRODUTO NUMBER(9,0),
	IC_ATIVO NUMBER(1,0) 
);

CREATE TABLE AVL.AVLTB005_MODELO_NOTA_NEGOCIO (
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	PZ_VALIDADE_MODELO_NOTA NUMBER(2,0),
	IC_REPACTUACAO_PRODUTO NUMBER(1,0),
	NO_MODELO_NOTA_NEGOCIO VARCHAR2(200),
	IC_MODELO_NOTA_ATIVO NUMBER(1,0) ,
	IC_SITUACAO_MODELO_NOTA CHAR(1) ,
	HH_VALIDADE_MODELO_NOTA VARCHAR2(5) ,
	NU_ACAO_PRODUTO NUMBER(9,0),
	IC_ENVIO_RETAGUARDA NUMBER(1,0),
	IC_NIVEL_CRITICIDADE_NOTA NUMBER(2,0) ,
	IC_MODELO_OUTRO_CANAL_ATNTO NUMBER(1,0) ,
	IC_PUBLICO_ALVO_MODELO_NOTA NUMBER(1,0) ,
	IC_MODELO_VINCULA_RTRO_FCHMO NUMBER(1,0) ,
	IC_MODELO_VINCULA_DOCUMENTO NUMBER(1,0) ,
	IC_MODELO_VINCULA_ANEXO NUMBER(1,0) ,
	TS_CRIACAO_MODELO_NOTA TIMESTAMP,
	TS_ULTIMA_ALTERACAO_MODELO TIMESTAMP,
	IC_CONTRATO_NOTA NUMBER(1,0) ,
	NU_TIPO_ATENDIMENTO NUMBER(3,0),
	IC_PORTAL_ASSINATURA_NOTA CHAR(1) ,
	IC_CONTRATACAO_AUTOMATICA CHAR(1)  
);

CREATE TABLE AVL.AVLTB030_FLUXO_ATNTO_MODELO (
	NU_FLUXO_ATENDIMENTO_MODELO NUMBER,
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	NU_ORDEM_ATENDIMENTO NUMBER(2,0),
	IC_FLUXO_ATENDIMENTO_ATIVO NUMBER(1,0)
);

CREATE TABLE AVL.AVLTB064_MODELO_NOTA_FAVORITO (
	NU_MODELO_NOTA_FAVORITA NUMBER(16,0),
	NU_MODELO_NOTA_NEGOCIO NUMBER(16,0),
	NU_MATRICULA_FAVORITO NUMBER(6,0),
	DT_ESCOLHA_FAVORITO DATE
);

