CREATE TABLE AVL.AVLTB019_NOTA_NEGOCIACAO (
	NU_NOTA_NEGOCIACAO NUMBER,
	NU_NEGOCIO_AGENCIA_VIRTUAL NUMBER,
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	DT_CRIACAO_NOTA DATE,
	DT_ULTIMA_MODIFICACAO_NOTA DATE,
	NU_MATRICULA_CRIACAO_NOTA NUMBER(6,0),
	NU_MATRICULA_MODIFICACAO_NOTA NUMBER(6,0),
	IC_TIPO_APROVACAO CHAR(1),
	DT_APROVACAO DATE,
	IC_TIPO_CANCELAMENTO CHAR(3),
	DE_MOTIVO_CANCELAMENTO VARCHAR2(140),
	DT_CANCELAMENTO DATE,
	DT_PRAZO_VALIDADE DATE,
	NU_SITUACAO_NOTA NUMBER,
	NU_AGENCIA_CONTA_CORRENTE NUMBER(4,0),
	NU_OPERACAO_CONTA_CORRENTE NUMBER(4,0),
	NU_CONTA_CORRENTE_ATENDIMENTO NUMBER(13,0),
	VR_SOLICITADO_NOTA_NEGOCIACAO NUMBER(14,2),
	NU_GRAVACAO_LIGACAO NUMBER,
	CO_ASSINATURAL_ELETRONICA VARCHAR2(100),
	TS_GRAVACAO_LIGACAO TIMESTAMP,
	TS_ASSINATURAL_ELETRONICA TIMESTAMP,
	QT_ITEM_NOTA_NEGOCIACAO NUMBER(2,0),
	IC_ORIGEM_NOTA_NEGOCIACAO NUMBER(1,0),
	TS_ACEITE_VOCAL_NOTA TIMESTAMP,
	DE_JUSTIFICATIVA_SITUACAO_NOTA VARCHAR2(200),
	CO_CHAVE_SEGURANCA_NOTA VARCHAR2(1000),
	NU_EQUIPE_CRIACAO_NOTA NUMBER(9,0),
	CO_HASH_VALIDACAO_NOTA VARCHAR2(150),
	IC_SISTEMA_CADASTRO_NOTA CHAR(1) DEFAULT 'A',
	VR_CAMPO_NOTA_NEGOCIACAO CLOB	
);


CREATE TABLE AVL.AVLTB020_ACAO_PRODUTO (
	NU_ACAO_PRODUTO NUMBER(9,0),
	DE_ACAO_PRODUTO VARCHAR2(100),
	NU_PRODUTO NUMBER(9,0),
	IC_ATIVO NUMBER(1,0) 
);


CREATE TABLE AVL.AVLTB005_MODELO_NOTA_NEGOCIO (
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	PZ_VALIDADE_MODELO_NOTA NUMBER(2,0),
	IC_REPACTUACAO_PRODUTO NUMBER(1,0),
	NO_MODELO_NOTA_NEGOCIO VARCHAR2(200),
	IC_MODELO_NOTA_ATIVO NUMBER(1,0) ,
	IC_SITUACAO_MODELO_NOTA CHAR(1) ,
	HH_VALIDADE_MODELO_NOTA VARCHAR2(5) ,
	NU_ACAO_PRODUTO NUMBER(9,0),
	IC_ENVIO_RETAGUARDA NUMBER(1,0),
	IC_NIVEL_CRITICIDADE_NOTA NUMBER(2,0) ,
	IC_MODELO_OUTRO_CANAL_ATNTO NUMBER(1,0) ,
	IC_PUBLICO_ALVO_MODELO_NOTA NUMBER(1,0) ,
	IC_MODELO_VINCULA_RTRO_FCHMO NUMBER(1,0) ,
	IC_MODELO_VINCULA_DOCUMENTO NUMBER(1,0) ,
	IC_MODELO_VINCULA_ANEXO NUMBER(1,0) ,
	TS_CRIACAO_MODELO_NOTA TIMESTAMP,
	TS_ULTIMA_ALTERACAO_MODELO TIMESTAMP,
	IC_CONTRATO_NOTA NUMBER(1,0) ,
	NU_TIPO_ATENDIMENTO NUMBER(3,0),
	IC_PORTAL_ASSINATURA_NOTA CHAR(1) ,
	IC_CONTRATACAO_AUTOMATICA CHAR(1)  
);


CREATE TABLE AVL.AVLTB030_FLUXO_ATNTO_MODELO (
	NU_FLUXO_ATENDIMENTO_MODELO NUMBER,
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	NU_ORDEM_ATENDIMENTO NUMBER(2,0),
	IC_FLUXO_ATENDIMENTO_ATIVO NUMBER(1,0)
);


CREATE TABLE AVL.AVLTB064_MODELO_NOTA_FAVORITO (
	NU_MODELO_NOTA_FAVORITA NUMBER(16,0),
	NU_MODELO_NOTA_NEGOCIO NUMBER(16,0),
	NU_MATRICULA_FAVORITO NUMBER(6,0),
	DT_ESCOLHA_FAVORITO DATE
);


CREATE TABLE AVL.AVLVM003_PRODUTO (
	NU_PRODUTO NUMBER(4,0),
	NU_DV_PRODUTO NUMBER(1,0),
	NO_PRODUTO VARCHAR2(120),
	NO_ABREVIADO_PRDTO VARCHAR2(40),
	CO_ULTIMA_SITUACAO CHAR(2),
	NU_ENTIDADE_O03 NUMBER(5,0),
	NU_OPERACAO_O23 NUMBER(5,0),
	NO_COMERCIAL_PRDTO VARCHAR2(40)
);


CREATE TABLE AVL.AVLTB017_CAMPO_MODELO_NOTA (
	NU_CAMPO_MODELO_NOTA NUMBER,
	NO_CAMPO_MODELO_NOTA VARCHAR2(300),
	IC_CAMPO_DEFINIDO NUMBER(1,0) DEFAULT 1 ,
	IC_CAMPO_EDITAVEL NUMBER(1,0) DEFAULT 1 ,
	IC_CAMPO_OBRIGATORIO NUMBER(1,0) DEFAULT 1 ,
	DE_ESPACO_RESERVADO VARCHAR2(100),
	IC_TIPO_DADO_CAMPO VARCHAR2(10) DEFAULT 'T' ,
	IC_TIPO_ENTRADA_CAMPO CHAR(2) DEFAULT 'IN' ,
	DE_CAMPO VARCHAR2(300),
	QT_CARACTER_CAMPO NUMBER(4,0),
	VR_INICIAL_CAMPO VARCHAR2(200),
	CO_MASCARA_CAMPO VARCHAR2(100)
);


CREATE TABLE AVL.AVLTB018_CAMPO_MODELO (
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	NU_CAMPO_MODELO_NOTA NUMBER,
	NU_ORDEM_CAMPO_MODELO NUMBER(3,0)
);


CREATE TABLE AVL.AVLTB046_CNDO_CAMPO_MULTIPLO (
	NU_CONTEUDO_CAMPO_MULTIPLO NUMBER,
	NU_CAMPO_MODELO_NOTA NUMBER,
	DE_CONTEUDO_CAMPO_MULTIPLO VARCHAR2(50)
);


CREATE TABLE AVL.AVLTB051_ROTEIRO_FCHMO_NOTA (
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	DE_MODELO_ROTEIRO_FECHAMENTO CLOB
);


CREATE TABLE AVL.AVLTB001_ATENDIMENTO_CLIENTE (
	NU_PROTOCOLO_ATNTO_CLNTE NUMBER(11,0),
	NU_CPF_CLIENTE NUMBER(11,0),
	NU_CNPJ_CLIENTE NUMBER(14,0),
	DT_INICIAL_CONTATO_CLNTE DATE,
	DT_FINAL_CONTATO_CLNTE DATE,
	DT_INICIAL_ATENDIMENTO_CLNTE DATE,
	DT_FINAL_ATENDIMENTO_CLNTE DATE,
	NU_MATRICULA_ATENDENTE NUMBER(6,0),
	IC_CANAL_ATENDIMENTO CHAR(1) DEFAULT 'W' ,
	NU_PROTOCOLO_PAI NUMBER(11,0),
	NO_CAMINHO_LOG_AUDIO VARCHAR2(4000),
	NO_CAMINHO_LOG_TEXTO VARCHAR2(4000),
	CO_CONFERENCIA VARCHAR2(100),
	DE_CONFERENCIA_URL VARCHAR2(4000),
	NO_CLIENTE VARCHAR2(200),
	DE_AVALIACAO_ATENDIMENTO VARCHAR2(200),
	IC_NOTA_AVALIACAO_ATENDIMENTO NUMBER(1,0),
	IC_SITUACAO_IDNFO_POSITIVA NUMBER(1,0) DEFAULT 0 ,
	IC_VALIDACAO_TOKEN_ATENDIMENTO NUMBER(1,0) DEFAULT 0 ,
	NU_UNIDADE_ATENDIMENTO NUMBER(4,0),
	CO_IDNTR_CONVERSA_APLICATIVO VARCHAR2(100),
	CO_TOKEN_CLIENTE_VISITANTE VARCHAR2(100),
	CO_USUARIO_ATNTE_APLICATIVO VARCHAR2(100),
	NU_PRTLO_PRSTR_INICIA_ATNTO NUMBER(14,0),
	DT_IDNFO_POSITIVA_CLIENTE DATE,
	DT_ENVIO_CHAVE_VALIDACAO_ATNTO DATE,
	TS_VALIDACAO_IDNFO_POSITIVA TIMESTAMP,
	DE_SITUACAO_IDNFO_POSITIVA VARCHAR2(20),
	NU_CANAL_ATENDIMENTO NUMBER(2,0)
);


CREATE TABLE AVL.AVLTB039_TIPO_DOCUMENTO_CLNTE (
	NU_TIPO_DOCUMENTO_CLIENTE NUMBER(3,0),
	NO_TIPO_DOCUMENTO_CLIENTE VARCHAR2(100),
	CO_CLASSE_DOCUMENTO_GED VARCHAR2(100)
);


CREATE TABLE AVL.AVLTB033_DOCUMENTO_CLIENTE (
	NU_CPF_CNPJ_CLIENTE NUMBER(14,0),
	IC_TIPO_PESSOA CHAR(2),
	TS_INCLUSAO_DOCUMENTO TIMESTAMP,
	NU_TIPO_DOCUMENTO_CLIENTE NUMBER(3,0),
	CO_GED_ANEXO VARCHAR2(76),
	VR_ARQUIVO_RECEBIDO BLOB,
	NO_ANEXO VARCHAR2(100),
	CO_MIMETYPE_ANEXO VARCHAR2(100),
	CO_EXTENSAO_ANEXO VARCHAR2(4),
	TS_VALIDACAO_DOCUMENTO TIMESTAMP,
	NU_MATRICULA_ATENDENTE NUMBER(6,0),
	IC_SITUACAO_DOCUMENTO_CLIENTE NUMBER(1,0) DEFAULT 1,
	IC_STCO_DOCUMENTO_CLIENTE NUMBER(1,0) DEFAULT 1 
);


CREATE TABLE AVL.AVLTB034_DCMNTO_NOTA_NGCCO (
	NU_NOTA_NEGOCIACAO NUMBER,
	NU_CPF_CNPJ_CLIENTE NUMBER(14,0),
	IC_TIPO_PESSOA CHAR(2),
	TS_INCLUSAO_DOCUMENTO TIMESTAMP,
	NU_TIPO_DOCUMENTO_CLIENTE NUMBER(3,0)
);


CREATE TABLE AVL.AVLTB023_ATENDIMENTO_NOTA (
	NU_NOTA_NEGOCIACAO NUMBER,
	NU_MATRICULA_ATENDIMENTO_NOTA NUMBER(6,0),
	TS_INICIO_ATENDIMENTO_NOTA TIMESTAMP,
	TS_CONCLUSAO_ATENDIMENTO_NOTA TIMESTAMP,
	IC_TIPO_UNDDE_DESIGNADA_ATNTO CHAR(1) DEFAULT 'A' ,
	NU_MATRICULA_CONCLUSAO_ATNTO NUMBER(6,0),
	TS_ENCERRAMENTO_NOTA TIMESTAMP,
	NU_EQUIPE_ATENDIMENTO NUMBER(10,0),
	CO_ACAO_ATENDIMENTO CHAR(2)
);


CREATE TABLE AVL.AVLTB003_ATENDIMENTO_NEGOCIO (
	NU_PROTOCOLO_ATNTO_CLNTE NUMBER,
	NU_NEGOCIO_AGENCIA_VIRTUAL NUMBER
);


CREATE TABLE AVL.AVLTB065_RLTRO_NOTA_NEGOCIACAO (
	NU_RELATORIO_NOTA_NEGOCIACAO NUMBER(16,0),
	NU_EQUIPE_ATENDIMENTO NUMBER(10,0),
	DE_RELATORIO_NOTA_NEGOCIACAO CLOB,
	NU_NOTA_NEGOCIACAO NUMBER(12,0),
	NU_PROTOCOLO_ATNTO_CLNTE NUMBER(12,0),
	DE_ACAO_PRODUTO VARCHAR2(100),
	NO_PRODUTO VARCHAR2(120),
	NU_CPF_CLIENTE NUMBER(11,0),
	NU_CNPJ_CLIENTE NUMBER(14,0),
	NO_CLIENTE VARCHAR2(200),
	DT_CRIACAO_NOTA DATE,
	DT_PRAZO_VALIDADE DATE,
	NU_SITUACAO_NOTA NUMBER(2,0),
	NU_MATRICULA_ATENDIMENTO_NOTA NUMBER(6,0),
	TS_INICIO_ATENDIMENTO_NOTA TIMESTAMP,
	TS_CONCLUSAO_ATENDIMENTO_NOTA TIMESTAMP,
	TS_ENVIO_REMETENTE TIMESTAMP,
	NU_MATRICULA_CRIACAO_NOTA NUMBER(6,0),
	NO_FLUXO_PASSO_ATENDIMENTO VARCHAR2(150)
);


CREATE TABLE AVL.AVLTB009_EQUIPE_ATENDIMENTO (
	NU_EQUIPE_ATENDIMENTO NUMBER(10,0),
	NU_MATRICULA_CRIACAO NUMBER(6,0),
	NU_UNIDADE_EQUIPE NUMBER(6,0),
	NU_NATURAL_EQUIPE NUMBER(9,0),
	NO_EQUIPE_ATENDIMENTO VARCHAR2(200),
	IC_EQUIPE_ATIVA NUMBER(1,0) DEFAULT 1 
);


CREATE TABLE AVL.AVLTB014_UNIDADE_DIGITAL_ATNTO (
	NU_UNIDADE_DIGITAL_ATNTO_VRTL NUMBER(6,0),
	NU_NTRL_UNDDE_DGTL_ATNTO_VRTL NUMBER(9,0),
	NU_UNIDADE_SR NUMBER(4,0),
	NU_NATURAL_SR NUMBER(9,0),
	IC_AGENCIA_ATIVO NUMBER(1,0) DEFAULT 1 ,
	ED_EMAIL VARCHAR2(120),
	IC_TIPO_UNIDADE CHAR(1),
	NO_CAIXA_POSTAL_UNIDADE_ATNTO VARCHAR2(75),
	CO_CATEGORIA_UNIDADE CHAR(2),
	IC_BLOQUEIO_ENVIO_NOTIFICACAO NUMBER(1,0) DEFAULT 0 
);


CREATE TABLE AVL.AVLTB002_NEGOCIO_AGNCA_VIRTUAL (
	NU_NEGOCIO_AGENCIA_VIRTUAL NUMBER,
	DT_CRIACAO_NEGOCIO DATE,
	IC_SITUACAO_NEGOCIO CHAR(1) DEFAULT 'E' ,
	NU_NEGOCIO_PAI NUMBER
);


CREATE TABLE AVL.AVLTB078_LOG_PLATAFORMA (
	NU_LOG_PLATAFORMA NUMBER(19,0),
	NU_TRANSACAO_SISTEMA NUMBER(4,0),
	NU_MATRICULA_ACAO NUMBER(6,0),
	TS_CRIACAO_LOG_PLATAFORMA TIMESTAMP,
	CO_ENDERECO_IP_USUARIO VARCHAR2(20),
	CO_VERSAO_SSTMA_AGNCA_VIRTUAL VARCHAR2(50),
	NU_NOTA_NEGOCIACAO NUMBER(12,0),
	NU_CPF_CNPJ_CLIENTE NUMBER(14,0),
	IC_TIPO_PESSOA CHAR(2),
	NU_ANO_MES_REFERENCIA NUMBER(6,0),
	DE_LOG_PLATAFORMA CLOB
);


CREATE TABLE AVL.AVLTB054_ASSINATURA_NOTA_NGCCO (
	NU_NOTA_NEGOCIACAO NUMBER,
	NU_CPF_CLIENTE_ASSINANTE_NOTA NUMBER(11,0),
	IC_TIPO_ASSINATURA_NOTA CHAR(2) DEFAULT '1' ,
	IC_ORIGEM_ASSINATURA_NOTA CHAR(2) DEFAULT '1' ,
	TS_ASSINATURA_NOTA_NEGOCIACAO TIMESTAMP,
	DE_ASSINATURA_NOTA_NEGOCIACAO VARCHAR2(3500)
);


CREATE TABLE AVL.AVLTB027_PENDENCIA_ATNTO_NOTA (
	NU_NOTA_NEGOCIACAO_CRIACAO NUMBER,
	NU_MATRICULA_ATENDIMENTO_CRIAC NUMBER(6,0),
	TS_INICIO_ATENDIMENTO_CRIACAO TIMESTAMP,
	TS_INCLUSAO_PENDENCIA_ATNTO TIMESTAMP,
	NU_TIPO_PENDENCIA NUMBER(5,0),
	DE_PENDENCIA_ATNTO_NOTA VARCHAR2(1200),
	NU_NOTA_NEGOCIACAO_SOLUCAO NUMBER,
	NU_MATRICULA_ATNTO_SOLUCAO NUMBER(6,0),
	TS_INICIO_ATENDIMENTO_SOLUCAO TIMESTAMP,
	TS_SOLUCAO_PENDENCIA_ATNTO TIMESTAMP
);



CREATE TABLE AVL.AVLTB007_SITUACAO_NOTA_NGCAO (
	NU_SITUACAO_NOTA NUMBER,
	DE_SITUACAO_NOTA VARCHAR2(50),
	IC_SITUACAO_PADRAO_NOTA NUMBER(1,0) DEFAULT 0 ,
	IC_SITUACAO_NOTA_ATIVO NUMBER(1,0) DEFAULT 1 
);



CREATE TABLE AVL.AVLTB070_TIPO_ATENDIMENTO (
	NU_TIPO_ATENDIMENTO NUMBER(3,0),
	NO_TIPO_ATENDIMENTO VARCHAR2(100)
	);

CREATE TABLE AVL.AVLTB006_COMENTARIO_ATNTO (
	NU_COMENTARIO_ATENDIMENTO NUMBER,
	DE_COMENTARIO_ATENDIMENTO VARCHAR2(1000),
	DT_COMENTARIO_ATENDIMENTO DATE,
	NU_PROTOCOLO_ATNTO_CLNTE NUMBER(11,0),
	NU_MATRICULA_ATENDENTE NUMBER(6,0)

);


CREATE TABLE AVL.AVLTB084_TIPO_FRMLO_CNTCO (
	NU_FORMALIZACAO_CONTRATACAO NUMBER(2,0),
	DE_FORMALIZACAO_CONTRATACAO VARCHAR2(50),
	IC_FORMALIZACAO_CNTCO_ATIVO CHAR(1) DEFAULT 'S' 
);


CREATE TABLE AVL.AVLTB085_FRMLO_CNTCO_MODELO (
	NU_MODELO_NOTA_NEGOCIO NUMBER,
	NU_FORMALIZACAO_CONTRATACAO NUMBER(2,0)
);


CREATE SEQUENCE AVL.AVLSQ064_MODELO_NOTA_FAVORITA
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE SEQUENCE AVL.AVLSQ001_NU_PROTOCOLO
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE SEQUENCE AVL.AVLSQ002_NU_NEGOCIO
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE SEQUENCE AVL.AVLSQ011_NU_NOTA_NEGOCIACAO
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE SEQUENCE AVL.AVLSQ078_NU_LOG_PLATAFORMA
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE SEQUENCE AVL.AVLSQ003_NU_COMENTARIO
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE SEQUENCE AVL.AVLSQ005_NU_CMTRO_ATENDIMENTO
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;